# Generated by Django 2.1.7 on 2019-05-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('Email', models.EmailField(help_text='Please enter a valid email address', max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Experience', models.IntegerField(default=2)),
                ('Notice_period', models.IntegerField(default=0)),
                ('Skill', models.SlugField(choices=[('python', 'Python'), ('java', 'Java')], default='Python')),
                ('Source', models.CharField(choices=[('RF', 'Referral'), ('JP', 'Job Portal')], max_length=10)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('reject', 'Reject')], default='Pending', max_length=10)),
                ('Rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-Created_at', '-Updated_at'],
            },
        ),
    ]
