# Generated by Django 2.1.7 on 2019-05-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='Email',
        ),
    ]
